---
- name: Gzip csv file(s)
  archive:
    dest:  '{{ item | regex_replace(".csv", ".gz.csv") }}'
    path: '{{ item }}'
  loop: '{{ created_csvs }}'
  register: gzip_info

- name: Set fact for created gz.csvs
  set_fact:
    created_gz_csvs: '{{ gzip_info.results | map (attribute="dest") | list }}'

- name: Get stats on the gz.csv file(s)
  stat:
    checksum_algorithm: md5
    path: '{{ item }}'
  loop: '{{ created_gz_csvs }}'
  register: gz_csv_info

- debug:
    var: gz_csv_info